### ISSUE TITLE
outsource modules in respective repos with submodules

### ISSUE THREAD

**Issue by SebRut** [JankGaming/jankbot-modules#3]
This way, there's a central repo to find all kind of modules but each modules code can be maintained by itself. For example https://github.com/SebRut/jankbot-modules

**Comment by twisterghost** [comment]
This could be a good temporary solution. Down the road I'm considering adding functionality for jankbot to manage modules itself, and to have modules installable via npm or something.

I'll allow pull requests with either submodules or native directories until a more cohesive solution is built in to Jankbot. I'll also plan to pull JankDota's modules out into their own repos.
