### ISSUE TITLE
coins - balance issue

### ISSUE THREAD

**Issue by SebRut** [JankGaming/jankbot-modules#4]
When one of my users uses the blaance command , he gets the following answer: "Message sent to [BLA]kamikaze: You have NaN Blaubeere(s)."

**Comment by twisterghost** [comment]
Can you check what value of that user's coin count in your `friendslist` file?

**Comment by SebRut** [comment]
It's null, I sent him some coins earlier.

Michael Barrett notifications@github.com schrieb am Do., 18. Juni 2015
00:16:

**Comment by twisterghost** [comment]
Okay. I have seen this issue before. I'll look into it and make coin transfer handling more strict with its typing.

**Comment by twisterghost** [comment]
This should be fixed now in c2a3bc72e83198948b0f5a6b3af641c01e090b6b. If the problem persists, open another issue. Try doing `coin reset` if there are still issues.
