### ISSUE TITLE
Using the 'coin give' command for users who have no balance results in a null balance.

### ISSUE THREAD

**Issue by beatyt** [JankGaming/jankbot-modules#6]
Coins show up as NaN to user.

![nan-coins](https://cloud.githubusercontent.com/assets/1040103/9389880/78f47162-473b-11e5-916e-4dc0d10c4a53.GIF)

Coins value is null.

![null-coins](https://cloud.githubusercontent.com/assets/1040103/9389881/78faf8f2-473b-11e5-8b79-369f6591398b.GIF)

I think the problem is caused by no check for things like NaN and null values, only undefined is checked for.

**Comment by beatyt** [comment]
Sorry nevermind I messed up >.<

**Comment by twisterghost** [comment]
Do you mind giving more info about what happened for you? I've seen this behavior in the past and have tried to fix it so far. I haven't seen it recently, though.

**Comment by beatyt** [comment]
My branch was not up-to-date ^.^'

**Comment by twisterghost** [comment]
Hah, ok. It's all good. This will be in npm soon and hopefully will remove the need to stay up-to-date beyond just updating from npm.
